### PR TITLE
Improve M1 compatibility

### PR DESCRIPTION
**Pull request by Lahphim**
## What happened

The current script doesn't support properly installing Homebrew to the correct directory based on the current chips either Apple Silicon or intel.

Screen Shot 2565-03-14 at 23 45 00
 
## Insight

- Make it flexible with the Homebrew directory
- Remove `Keybase` as it  still doesn't support M1 yet
- Update the Postgres path for creating a new user

Reference changes: https://github.com/thoughtbot/laptop/pull/602
 
## Proof Of Work

Screen Shot 2565-04-04 at 09 53 03

### CODE REVIEW

**Review by edgarss — APPROVED** [review]
LGTM

**Comment by luongvo** [comment]
> Remove Keybase as it doesn't support M1 anymore

@Lahphim Do you mean `as it still does not support M1 yet` instead? I can't official announcement for no M1 support here https://github.com/keybase/keybase-issues/issues/3968 🤔

**Review by tyrro — APPROVED** [review]

**Comment by Lahphim** [comment]
> > Remove Keybase as it doesn't support M1 anymore
> 
> @Lahphim Do you mean `as it still does not support M1 yet` instead? I can't official announcement for no M1 support here [keybase/keybase-issues#3968](https://github.com/keybase/keybase-issues/issues/3968) 🤔

Yeah, I should say that `it still does not support M1 yet` 💪

**Comment by olivierobert** [comment]
It would be good to have [the link to the PR that implements the same solution](https://github.com/thoughtbot/laptop/pull/602) on the original laptop script repository from Thoughtbot in the `Insights` section to give confidence in the changes 💭

**Comment by Lahphim** [comment]
@luongvo and @olivierobert I've updated the PR's description already

**Comment by olivierobert** [comment]
For Keybase, it can work via Rosetta 2 so we might not need to remove it: https://doesitarm.com/app/keybase/

**Comment by Lahphim** [comment]
> For Keybase, it can work via Rosetta 2 so we might not need to remove it: https://doesitarm.com/app/keybase/

@olivierobert Do you mean that we have to set the terminal to run with `rosetta2` before running the `mac` script?

I used to set it like that before, it will set the path of homebrew to `/usr/local` and for the docker it will download the version for `intel` (https://github.com/Homebrew/homebrew-cask/blob/master/Casks/docker.rb#L2). 🤔

Should we let the user install that manually or the other way?

**Comment by olivierobert** [comment]
@Lahphim No, I think we do not need to remove Keybase from the list of installed applications by default. Users with an M1 can just turn on the Rosetta mode for that application manually: https://www.macworld.com/article/338843/how-to-force-a-native-m1-mac-app-to-run-as-an-intel-app-instead.html

**Comment by Lahphim** [comment]
> @Lahphim No, I think we do not need to remove Keybase from the list of installed applications by default. Users with an M1 can just turn on the Rosetta mode for that application manually: https://www.macworld.com/article/338843/how-to-force-a-native-m1-mac-app-to-run-as-an-intel-app-instead.html

@olivierobert I bring `Keybase` back and re-install it again ... 
I got this message. 
Screen Shot 2565-04-07 at 10 37 16

What do you think if I add another function like this to just install that package for the laptop with intel chip?

```
append_general_intel_dependencies() {
  fancy_echo "Appending web's dependencies to Brewfile"

  tee -a "$HOME/.Brewfile" <<-EOF
    # General apps
    cask "keybase" unless File.directory?("/Applications/Keybase.app")
EOF
}
```

**Comment by olivierobert** [comment]
@Lahphim Alright, in that case, then yes let's only install Keybase for non-M1 machines. Also, let's add a note in the README about non-M1 compatible dependencies.

**Comment by Lahphim** [comment]
> @Lahphim Alright, in that case, then yes let's only install Keybase for non-M1 machines. Also, let's add a note in the README about non-M1 compatible dependencies.

@olivierobert Updated here https://github.com/nimblehq/laptop/pull/31/commits/559891a768f37ae9acd669838045060a01679b11

**Comment by liamstevens111** [comment]
After running into problems with the original script on a M1 Macbook Pro from the office last night, this script seemed to fix the problems, thank you. 

However, when installing the Android dependencies Java failed to install. I fixed this by manually running ``brew install --cask temurin``

**Comment by liamstevens111** [comment]
After running into problems with the original script when setting up a M1 Macbook Pro last night, your changes fixed those problems, thank you.

However, although unrelated to the M1 issue, I received the following error when installing Java for the Android dependencies:
``Error: Cask 'java' is unavailable: No Cask with this name exists.``

I fixed this problem by manually running:

`` brew install --cask temurin`` 

Which installed OpenJDK version 18.

Some resources I used:

[https://stackoverflow.com/questions/70749800/installing-jdk17-on-mac-with-brew](https://stackoverflow.com/questions/70749800/installing-jdk17-on-mac-with-brew)

[https://github.com/AdoptOpenJDK/homebrew-openjdk](https://github.com/AdoptOpenJDK/homebrew-openjdk)

**Comment by Lahphim** [comment]
> After running into problems with the original script when setting up a M1 Macbook Pro last night, your changes fixed those problems, thank you.
> 
> However, although unrelated to the M1 issue, I received the following error when installing Java for the Android dependencies: `Error: Cask 'java' is unavailable: No Cask with this name exists.`
> 
> I fixed this problem by manually running:
> 
> ` brew install --cask temurin`
> 
> Which installed OpenJDK version 18.
> 
> Some resources I used:
> 
> [https://stackoverflow.com/questions/70749800/installing-jdk17-on-mac-with-brew](url)
> 
> [https://github.com/AdoptOpenJDK/homebrew-openjdk](url)

Thank @liamstevens111 for issue detail 🙏

I check in the [brew](https://brew.sh/), it seems that they don't have `java` in `cask` mode anymore.

Screen Shot 2565-04-20 at 18 58 57

So I'll replace that with `temurin` anyway 💪

Screen Shot 2565-04-20 at 18 59 07

This change here >> https://github.com/nimblehq/laptop/pull/31/commits/3c1cbe2f094b9a79b24c4e1c0838ebe270f43ce6

**Review by olivierobert — APPROVED** [review]

**Pull request merged**
